version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  mongo_seed:
    image: mongo:latest
    links:
      - mongodb
    volumes:
      - ./db:/tmp
    command:
        mongoimport --host mongodb --db assesment --collection users --type json --file /tmp/users.json --jsonArray
  

    